language: go

sudo: false

matrix:
  include:
    - go: "1.8.x"
    - go: "1.9.x"
    - go: "1.10.x"
    - go: "1.11.x"
      env: GO111MODULE=off
    - go: "1.11.x"
      env: GO111MODULE=on
    - go: tip
  script:
    - go test -coverprofile=coverage.txt -covermode=atomic
  after_success:
    - bash <(curl -s https://codecov.io/bash)
